<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="Bunit" />
		<Using Include="Bunit.TestDoubles" />
		<Using Include="Microsoft.Extensions.DependencyInjection" />
		<Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="bunit" Version="2.10.3" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
		<PackageReference Include="coverlet.collector" Version="10.0.1">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>



	<ItemGroup>
		<PackageReference Include="MSTest.TestAdapter" Version="4.4.0" />
		<PackageReference Include="MSTest.TestFramework" Version="4.4.0" />
	</ItemGroup>



	<ItemGroup>
	  <ProjectReference Include="..\BlazorHolTestApp\BlazorHolTestApp.csproj" />
	</ItemGroup>

</Project>
